In [2]:
import pandas  as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

1. 데이터 불러오기

In [9]:
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

2. 특성(X)과 정답(Y) 분리 및 데이터 분할

In [10]:
X = df.drop('target', axis=1)
y = df['target']

In [11]:
df['target']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [12]:
X.shape

(150, 4)

3. 데이터 전처리(스케일링)

In [15]:
X_train, X_test, y_train, y_test = train_test_split( X , y , test_size=0.2, random_state=42)

In [16]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]

In [17]:
 X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2
110                6.5               3.2                5.1               2.0
12                 4.8               3.0                1.4               0.1
36                 5.5               3.5                1.3               0.2
9                  4.9               3.1                1.5               0.1
19                 5.1               3.8                1.5               0.3
56                 6.3               3.3                4.7               1.6
104                6.5               3.0                5.8               2.2
69                 5.6               2.5                3.9               1.1
55                 5.7               2.8                4.5               1.3
132                6.4               2.8                5.6               2.2
29                 4.7               3.2                1.6               0.2
127                6.1               3.0                4.9               1.8
26                 5.0               3.4                1.6               0.4
128                6.4               2.8                5.6               2.1
131                7.9               3.8                6.4               2.0
145                6.7               3.0                5.2               2.3
108                6.7               2.5                5.8               1.8
143                6.8               3.2                5.9               2.3
45                 4.8               3.0                1.4               0.3
30                 4.8               3.1                1.6               0.2

In [18]:
y_train

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64

3. 데이터 전처리(스케일링)

In [21]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

4. 모델 생성 및 학습

In [22]:
model = DecisionTreeClassifier(max_depth=3, random_state=42)
model.fit( X_train_scaled , y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [24]:
y_pred = model.predict(X_test_scaled)

In [25]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [26]:
accuracy = accuracy_score( y_test, y_pred)

In [29]:
print(f'모델 정확도 : {accuracy:.3f}')

모델 정확도 : 1.000